### ISSUE TITLE
Intl.RelativeTimeFormat needs a polyfill

### ISSUE THREAD

**Issue by InterLinked1** [InterLinked1/chromefill#1]
This needs a polyfill: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/RelativeTimeFormat

**Comment by Vangelis66** [comment]
Unfortunately :cry: , this has now become the reason the **Spotify Web Player** is currently producing a **blank page** in [Chromium<**71**]-based web browsers: 

![360EEv11_spotifyWP](https://user-images.githubusercontent.com/9669492/170873663-be1aba02-f100-46ad-92fc-1e650689f02a.JPG)

Above is with **360EEv11**, Chromium **69** based, popular among **XP**+**Vista** users :stuck_out_tongue_winking_eye: ...

Sample URI: "https://open.spotify.com/show/2XHy0waKckPLULstsawBwP"

FWIW, "**Spotify Web**" used to load fine ca. 2 months ago, so that's a recent change implemented by them :angry: ; why can't they just let "sleeping dogs lie" ? :rage:

**Comment by InterLinked1** [comment]
There do actually seem to be a couple polyfills out there for this, e.g.:

- https://github.com/wessberg/intl-relative-time-format
- https://github.com/catamphetamine/relative-time-format
- https://polyfill.io/v3/polyfill.min.js?features=Intl

However, my attempts at integrating them into this extension thus far have failed. If anyone has the time to figure it out before I do, pull requests are always welcome.

**Comment by Vangelis66** [comment]
> my attempts at **integrating them into this extension** thus far have **failed**.

... Same here :disappointed: :cry: - and I'm not a coder!
However, as I am an obstinate person :stuck_out_tongue_winking_eye: , in the end I concocted a Violentmonkey **userscript** that uses the `polyfill.io` online service, achieving the desired effect: 
```js
// ==UserScript==
// @name        Add Intl.RelativeTimeFormat support
// @version     0.0.1
// @description Polyfills 'Intl.RelativeTimeFormat()', first implemented in Chromium 71
// @namespace   polyfill.io
// @include     *
// @run-at      document-start
// @require     https://polyfill.io/v3/polyfill.min.js?features=Intl.RelativeTimeFormat,Intl.RelativeTimeFormat.~locale.en
// @grant       none
// ==/UserScript==

<!-- Polyfill Intl.RelativeTimeFormat, its dependencies & 'en' locale data -->
```
Now the **Spotify Web Player** does load and function in my **Chromium 69 derived** browser: 

![spot2](https://user-images.githubusercontent.com/9669492/170900607-77db03f3-0b2a-48c3-b99d-e284828639ec.JPG)

The Spotify `ServiceWorker` still **doesn't register**, but that's a small price to pay...

From my testing, **Violentmonkey v2.13.0** is the last **fully** compatible with **Chromium 69**; the last fully compatible **BETA releas**e is [v2.13.0.10](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.0.10); haven't tested how **Tampermonkey** fares... :wink:

**Comment by InterLinked1** [comment]
Interestingly, I no longer seem to get this error on the link provided above.
Do you know of any other sites that triggered this error? I don't remember off hand.

**Comment by Vangelis66** [comment]
> I no longer seem to get this error on the link provided above.

On **May 31st**, ca. two days after I posted [2](https://github.com/InterLinked1/chromefill/issues/1#issuecomment-1140460335), **Spotify** revisited their **Web Player**; minimum browser requirements have been somewhat lowered, to **Firefox 60.0** & **Chrome 66.0**: 

https://support.spotify.com/gr/article/web-player-help/

![sw](https://user-images.githubusercontent.com/9669492/175402541-1737fbb1-ec79-4470-ae76-80afb161c83d.JPG)

Two observations: 
1. On such "old" browser versions (at least), the **Web Player no longer requires** the `Intl.RelativeTimeFormat()` constructor, so yes, **your latest post is right** (if you tested in Chrome **70.0**). 😜 
2. Given that 98.0% of **Spotify content for registered users is DRM'ed** (😠), I find it a tad surprising they've chosen to support as low a Fx version as 60.0 and as low a Chrome version as 66.0; in-browser DRM demands Google's **Widevine CDM**, its latest version (4.10.2449.0?) itself requires at least **FirefoxESR 91.x.x** and **Chrome 69.0** - but at least non-DRM content (mostly Podcasts) can be played-back in older Chromium and Firefox forks; even **UXP** browsers (Pale Moon, Serpent 52, etc.) work for non-DRM Spotify content, that doesn't require a log-in: 
https://open.spotify.com/show/2XHy0waKckPLULstsawBwP

> Do you know of any other sites that triggered this error? I don't remember off hand.

Another site was recently reported in the MSFN forums: 
https://socialclub.rockstargames.com/

In my Chromium **69.0** fork, the URL yields a **blank tab**, JS console reports: 
```
Uncaught (in promise) TypeError: Intl.Locale is not a constructor  VM388 6340.js:1
    at VM388 6340.js:1
    at Set.forEach (<anonymous>)
    at e.BestFitMatcher (VM388 6340.js:1)
    at e.ResolveLocale (VM388 6340.js:1)
    at e.match (VM388 6340.js:1)
    at e.shouldPolyfill (VM389 intl-should-polyfill.js:1)
    at u (VM287 app.js:62)
```
The URL loads as expected if `Intl.RelativeTimeFormat()` support is "introduced" via the userscript I posted in [4](https://github.com/InterLinked1/chromefill/issues/1#issuecomment-1140588620) 😜 : 
![rsg](https://user-images.githubusercontent.com/9669492/175413083-e339e924-ea74-4559-bced-f7936a6dddb0.JPG)
